### ISSUE TITLE
`PIPELINE_CSS` and `PIPELINE_JS` in app settings.

### ISSUE THREAD

**Issue by miki725** [cyberdelia/django-pipeline#197]
Is there any way to add configurations to `PIPELINE_CSS` and `PIPELINE_JS` from Django apps?

I have some reusable Django apps I use across my projects and some of them use Django Pipeline. To properly configure them, I end up copying the `PIPELINE_CSS` and `PIPELINE_JS` into all the projects setting files. That however I feel does not follow the DRY principle so I wonder if there is any way of including the Pipeline settings directly within the apps so that I don't have to copy the configs.

If there is no existing way to do it, is there any way of incorporating this functionality into Pipeline. Not sure how that should be implemented though.

**Comment by whatisjasongoldstein** [comment]
I've been using this as a workaround. https://github.com/whatisjasongoldstein/django-pipeline-helpers

**Comment by miki725** [comment]
cool. didnt know about it. I got tired of installing from my fork which is pretty outdated at this point.

**Comment by miki725** [comment]
seems like there is no need for this PR due to https://github.com/whatisjasongoldstein/django-pipeline-helpers and no interest in merging so closing.
