### ISSUE TITLE
Can't use django-pipeline > 1.3 due to django-storages (Path issue)

### ISSUE THREAD

**Issue by schmitch** [cyberdelia/django-pipeline#391]
Hello, currently I can't use django-pipeline 1.4 since I will always ran into the issue that the function ```def path(self, name):``` is getting triggered. Since I've run a Django-storages backend which doesn't implement the function I can't use django-pipeline anymore.
Version 1.3 worked great Version 1.4 broke everything up.

I'm running django-pipeline 1.3, with a sass compressor and a HashedFileMixin and a S3BotoStorage as my S3 Backend. Currently I'm on Python3 and fixed some things of S3BotoStorage and I will fix more and more. But the ```def path(self,name):``` can't be implemented in remote storages so there should be some other solutions.

If you need more details just ask.

**Comment by jdp** [comment]
I'm seeing the same issue, trying to use the S3 recipe from the [Using with other storages](http://django-pipeline.readthedocs.org/en/latest/storages.html#using-with-other-storages) section. It looks like it will always cause [this exception](https://github.com/django/django/blob/a7c256cb5491bf2a77abdff01638239db5bfd9d5/django/core/files/storage.py#L116) to be raised through [here](https://github.com/cyberdelia/django-pipeline/blob/master/pipeline/compilers/__init__.py#L36). I'm using django-pipeline==1.4.3 and django-storages==1.1.8.

**Comment by cyberdelia** [comment]
Fixed in #409.
