### ISSUE TITLE
STATIC_ROOT set to /tmp/ when PIPELINE_ENABLED = False

### ISSUE THREAD

**Issue by Remiz** [cyberdelia/django-pipeline#394]
I noticed since the new 1.4 that STATIC_ROOT is set to /tmp/tmp[random characters] when my settings is indicating PIPELINE_ENABLED = False (which I use for my local development and test runner). That's a behaviour that's not existing in 1.3.

Also not sure why but it seems my tests are running slower since the new version of pipeline... Maybe it's just me.

**Comment by owais** [comment]
This is a huge issue as JS packs that depend on node_modules fail. node just can't find the installed modules as they are not in the parent directory of /tmp/***

**Comment by Remiz** [comment]
That issue seems fixed for me with the latest version. Thanks for the fix!
Now I don't know if I'm the only one but my tests are running slower (114 s. VS 32 s. with pipeline 1.3)... Is anyone else noticed an issue with that or maybe the issue is within my tests?

**Comment by Remiz** [comment]
I'm coming back to say that my issue with my test is resolved. I specified that my tests should run with PIPELINE_ENABLED = False, and this settings caused these to run in 2 minutes, when I remove this settings my whole test suite runs in 16 seconds :).
Anyway, thanks for fixing the issue. I'm closing this ticket.
