### ISSUE TITLE
Compiler 1.4.2 doesn't support relative path import

### ISSUE THREAD

**Issue by TontonMax** [cyberdelia/django-pipeline#406]
Hi, 
This line:

```
@import "../../../../../bower_components/bootstrap/less/bootstrap";
```

breaks on 1.4.2 with a compiler error like:
```
pipeline.exceptions.CompilerError: FileError: <...> wasn't found in /tmp/tmpprPjWp/<...>
```

Fallbacking on version 1.3.23, is works. 
I see it as a regression, but maybe that is what you want?
Best regards, 
Max

**Comment by bardo** [comment]
Try it under 1.4.3, I'm not sure it will solve your problem but at least it won't chdir to /tmp, and debugging should be easier.

**Comment by cyberdelia** [comment]
As indicated by @bardo, this should not be a problem with new version of pipeline.
