### ISSUE TITLE
Please document PIPELINE_ENABLED in directions for upgrading to 1.4

### ISSUE THREAD

**Issue by tammyalexandra** [cyberdelia/django-pipeline#408]
The flag is being used in a different way from 1.3, which creates a backwards incompatibility in some set-ups:

http://stackoverflow.com/questions/27771184/x-amz-acl-being-set-incorrectly-when-using-collectstatic-with-latest-version-of

Thank you!

**Comment by cyberdelia** [comment]
``PipelineMixin`` don't use ``PIPELINE_ENABLED`` anymore, so I guess this is not a problem anymore.
