### ISSUE TITLE
Exclude specific files from versioning

### ISSUE THREAD

**Issue by alexdoe23** [cyberdelia/django-pipeline#411]
Hi,

Is there a way to exclude specific files from versioning? Few examples would include files like: robots.txt, all favicons, images uses for emoticons (I have hundreds of these, no need to keep a separate copy with hash info in the filename).

I've tried several settings in STATICFILES_FINDERS but nothing seems to work.

Any help would be really appreciated. Using Django 1.6.9 with django-pipeline 1.4.2

Thanks.

**Comment by cyberdelia** [comment]
Not as far as I know, the versioning is done by ``django.contrib.staticfiles``.
