### ISSUE TITLE
SASS issue in latest upgrade

### ISSUE THREAD

**Issue by arnaudlimbourg** [cyberdelia/django-pipeline#412]
In commit https://github.com/cyberdelia/django-pipeline/commit/495c2f840f87f16f5a68304e2a4dc6bae4b449ed removing the semi-colon breaks usage with regular ruby gem.

I get an error like
```
pipeline.exceptions.CompilerError: File project.css is a CSS file.
Did you mean: sass --update project.scss:project.css
```

downgrading to 1.4.2 solves the issue. The sass executable expects a colon between the two filenames, the compiler fails since it was removed.

The issue being that one or the other works at a time.

I suppose a way to solve this would be to add an extra ```PIPELINE_SASS_LIBSASS = False``` by default to alternate between the two syntax. Toughts?

**Comment by kevin-brown** [comment]
This is related to https://github.com/cyberdelia/django-pipeline/issues/404, and there are plenty of implementations using libsass that were affected before.

```bash
$ sass --update --help
Usage: sass [options] [INPUT] [OUTPUT]
[...]
        --watch                      Watch files or directories for changes.
                                     The location of the generated CSS can be set using a colon:
                                       sass --watch input.sass:output.css
                                       sass --watch input-dir:output-dir
        --update                     Compile files or directories to CSS.
                                     Locations are set like --watch.
```

Is there a reason why we are using the `--update` parameter by default? Shouldn't `sass infile outfile` work?

**Comment by arnaudlimbourg** [comment]
It seems to work properly

```
sass project.scss foo.css
# ls show the css and a  source map  file
```
