### ISSUE TITLE
1.4.3 shipping with old compressed templatetags

### ISSUE THREAD

**Issue by HenrikOssipoff** [cyberdelia/django-pipeline#414]
1.4.0 marked the old templatetags as backwards incompatible, but it appears that at least 1.4.3 ships with the old templatetags, as well as the new ones - making the change rather backwards compatible.

Since the file is not present in the Git repository anymore, I suspect a small error in the packaging.

**Comment by cyberdelia** [comment]
Thanks! 
Fixed in 1.4.4.1.
