### ISSUE TITLE
mozilla.org using pipeline

### ISSUE THREAD

**Issue by pmclanahan** [cyberdelia/django-pipeline#425]
Just wanted to let you know and wasn't sure how else to contact you. We just pushed the changes live today. Thanks for the great work!

* https://www.mozilla.org/
* https://github.com/mozilla/bedrock

**Comment by pmclanahan** [comment]
Oh, and feel free to add it to your "using pipeline" docs page if you'd like.

**Comment by cyberdelia** [comment]
@pmclanahan Really glad to hear! I added a word [about it](https://github.com/cyberdelia/django-pipeline/commit/4787189407ac810d39f835a21c0ac6f3d470d96a).

**Comment by cyberdelia** [comment]
If someone from Mozilla is willing to complete pipeline documentation to introduce how to setup pipeline with whitenoise (and vice-versa). It would be really, really, really lovely :heart:
