### ISSUE TITLE
collectstatic ignores sass errors

### ISSUE THREAD

**Issue by cameel** [cyberdelia/django-pipeline#430]
I'm trying to update my sass to the lastest version (3.2.14) and I have discovered that django-pipeline completely ignores its errors because they get printed to `stdout`, not `stderr`. The command is simply:

``` bash
/usr/bin/env sass --compass somefile.sass somefile.css
```

sass prints:

`ERROR: Cannot load compass.`

to `stdout` and nothing to `stderr`. The sass process returns a non-zero error code though and I think that this is a more reliable way to check if it succeeded.

My problem is obviously that compass is missing (I may have uninstalled it by mistake) but I had to trace through the code to discover that.

**Comment by cyberdelia** [comment]
I have no idea why we never checked the return code :eyes:
I fixed that in fa6aa614f0d08ab3e38a5912882190feb76f7404.
This should help figuring out something is wrong, but it would also be nice if ``sass`` used ``stderr`` properly (so you get the error message in the exception).

**Comment by cameel** [comment]
Maybe `sass`' `stdout` could be written to a log file if it fails? At least when in debug mode. In development log output is usually printed to the console and that would be helpful.
