### ISSUE TITLE
Generate index.html once with collectstatic

### ISSUE THREAD

**Issue by Remco47** [cyberdelia/django-pipeline#432]
We use a single-page app design so all of our HTML is static. We currently need a Django template for index.html just to let Pipeline insert the script tags. We'd rather have Pipeline generate index.html as well, so it is created once during collectstatic.

**Comment by cyberdelia** [comment]
You can hook yourself into ``collectstatic`` mechanism like [pipeline](https://github.com/cyberdelia/django-pipeline/blob/master/pipeline/storage.py#L16).
But I'm afraid that's out of scope for pipeline.
