### ISSUE TITLE
Warning with Django1.8

### ISSUE THREAD

**Issue by peterseymour** [cyberdelia/django-pipeline#447]
Django1.8 gives a deprecation warning for the use of 

from django.utils import importlib

in pipeline/utils.py

Can this be replaced with 

import importlib

**Comment by cyberdelia** [comment]
I'm lagging a bit behind, sorry, see #417.

**Comment by cyberdelia** [comment]
It should be fixed in the freshly released 1.5.x.

**Comment by peterseymour** [comment]
Thank you 

On 2015-04-25 23:16, Timothée Peignier wrote: 

> It should be fixed in the freshly released 1.5.x. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 

Peter Seymour
Zanopha

mobile +44 (0)7815 059903
www.zanopha.com 

Links:
------
[1]
https://github.com/cyberdelia/django-pipeline/issues/447#issuecomment-96287414

**Comment by dcwatson** [comment]
This warning is still raised due to this import:

https://github.com/cyberdelia/django-pipeline/blob/master/pipeline/utils.py#L11

If you're no longer supporting Python 2.6, it can just be `import importlib`.
