### ISSUE TITLE
Javascript templates with Angular

### ISSUE THREAD

**Issue by sikko** [cyberdelia/django-pipeline#450]
I can see that some libs have been written to help with javascript template integration:

http://django-pipeline.readthedocs.org/en/latest/templates.html#using-it-with-your-favorite-template-library

But are there any ways to use the javascript templates with angular's templateCache system?

**Comment by mfollett** [comment]
I'm working on an implementation that can do this, so there is a way to do it. I wrote a custom compiler that just calls out to gulp to use gulp-ng-annotate.

It wasn't terribly difficult to do, but I'm not sure how I would make it sufficiently generic as to package it up for others.

**Comment by tkazec** [comment]
I did this recently.

```python
import json
import os

from pipeline.compilers import CompilerBase

class AngularCompiler(CompilerBase):
    output_extension = 'tmpl'
    
    output_tmpl = """
    angular.module("app").run(function ($templateCache) {{
        $templateCache.put("/{path}", {text});
    }});
    """
    
    def match_file(self, path):
        return path.endswith('.html')
    
    def compile_file(self, infile, outfile, outdated=False, force=False):
        if not outdated and not force:
            return
        
        with open(infile, 'r') as rf:
            with open(outfile, 'w') as wf:
                wf.write(self.output_tmpl.format(
                    path=os.path.relpath(infile, <YOUR_BASE_DIR>),
                    text=json.dumps(rf.read())
                ))
```

**Comment by sikko** [comment]
Thanks, that worked for me
