### ISSUE TITLE
Don't delete history from HISTORY

### ISSUE THREAD

**Issue by nedbat** [cyberdelia/django-pipeline#463]
I am running a really old version of django-pipeline (1.2.x), and wanted to assess what has changed.  I looked in HISTORY, and it only mentions 1.5.0.  Shouldn't HISTORY retain history?

**Comment by cyberdelia** [comment]
A long history file is sort of not really useful either, I should probably do upgrade guide for each versions.
But hopefully, git retains history, so, here is some more history:
https://github.com/cyberdelia/django-pipeline/blob/1.2.X/HISTORY.rst
https://github.com/cyberdelia/django-pipeline/blob/1.3.x/HISTORY.rst
