### ISSUE TITLE
Serving gzipped static files broken in 1.5.3

### ISSUE THREAD

**Issue by fxthomas** [cyberdelia/django-pipeline#488]
Hello,

When upgrading from 1.5.1 to 1.5.3, precompiled CSS and JS files suddenly gained a `.gz` extension in the output of `{% static %}` template tags and CSS `@import` rules. The relevant commit is most likely c360a2add.

As a result, at least Firefox is unable to load CSS and JS files, and shows messages such as :

    The stylesheet http://xxxx/static/admin/css/yyyyy.4898e2e9983d.css.gz was not loaded because its MIME type, "application/gzip", is not "text/css".

uWSGI can automatically (with `--static-gzip-all`) select either the gzipped or the non-gzipped version of a static file, depending on the request's `Accept-Encoding` header, so there is no need for the `.gz` extension, at least in my case. I believe Nginx is able to do this as well. Is that the correct way of serving gzipped files or is there something I'm not aware of?

Thanks for your help!

**Comment by Siltaar** [comment]
Pipeline was already creating pre-compressed .gz files for every managed files in previous versions, but this files were not served.

Nginx and uWSGI are able to compress statically served files on the fly, but it's not the same as serving pre-compressed files.

So, Pipeline (used with uWSGI and Nginx), in version 1.5.3, is just missing Content-Encoding HTTP header (to set to gzip), to achieve the best static file serving option.

**Comment by cyberdelia** [comment]
Looks like uWSGI, Whitenoise detect the gzip file, so I might as well revert this change.

**Comment by fxthomas** [comment]
Ah, thanks! After checking, all the major players for serving Python web apps seem to support this out of the box.

Only Apache does not have a dedicated option for serving precompressed static files, and thus needs the aforementioned [header tweaking](https://feeding.cloud.geek.nz/posts/serving-pre-compressed-files-using/). I may have missed something though, as I haven't used it in a while.

**Comment by cyberdelia** [comment]
Closing since next version will stop returning .gz urls.
